### PR TITLE
Fix promise require call to work with npm@3

### PR DESCRIPTION
**Pull request by jon-hall**
Addresses #27

### CODE REVIEW

**Comment by jon-hall** [comment]
Apologies it took me so long to get this sorted, it's been updated now though and continues to work with npm@3 and npm@2 (also tested across node v0.12 and v4).

I also had to update the npm test command to run with node v4 (replacing the --harmony-generators flag which is no longer valid), though I can remove that addition if that's not something you want getting bundled into this PR.

**Comment by rdkls** [comment]
+1
Thanks Jon

**Comment by admorphit** [comment]
Can we get this merged in now?

**Comment by SEAPUNK** [comment]
+1 Would like this to be merged in, as it forces me to use the fork in the meantime.

**Comment by jmar777** [comment]
@jon-hall sorry for the long delay in getting back to this, but it's now merged and published to NPM as v0.7.0. Thanks so much!

**Pull request merged**
